import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'

// Emits a seed file as an upsert. Content is updated; state, completed_at and
// the projected dates are left alone, so reloading never touches progress. Run
// `POST /api/reproject` afterwards to recompute projections from the new
// baselines.
//
// Pass a path to seed a different file, e.g. the tracked example:
//   node tools/seed/to-sql.mjs seed/roadmap.example.json

const root = new URL('../../', import.meta.url)
const input = process.argv[2] ?? 'seed/roadmap.json'
const seedPath = new URL(input, root)

if (!existsSync(seedPath)) {
  console.error(`${input} not found. The roadmap is private and lives outside this repository.`)
  console.error(`Copy seed/roadmap.example.json to seed/roadmap.json to start one.`)
  process.exit(1)
}

const raw = readFileSync(seedPath, 'utf8')
const seed = JSON.parse(raw)
const version = createHash('sha256').update(raw).digest('hex').slice(0, 12)

const text = (value) => `'${String(value).replaceAll("'", "''")}'`
const nullable = (value) => (value === null || value === undefined ? 'NULL' : text(value))
const json = (value) => text(JSON.stringify(value))

const statements = []

for (const item of seed.items) {
  statements.push(`INSERT INTO items (
  id, name, type, phase, skills, depends_on,
  baseline_start, baseline_end, projected_start, projected_end,
  price, link, notes, sort_order
) VALUES (
  ${text(item.id)}, ${text(item.name)}, ${text(item.type)}, ${item.phase},
  ${json(item.skills)}, ${json(item.dependsOn)},
  ${text(item.baselineStartDate)}, ${text(item.baselineEndDate)},
  ${text(item.baselineStartDate)}, ${text(item.baselineEndDate)},
  ${text(item.price)}, ${nullable(item.link)}, ${text(item.notes)}, ${item.sortOrder}
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  type = excluded.type,
  phase = excluded.phase,
  skills = excluded.skills,
  depends_on = excluded.depends_on,
  baseline_start = excluded.baseline_start,
  baseline_end = excluded.baseline_end,
  price = excluded.price,
  link = excluded.link,
  notes = excluded.notes,
  sort_order = excluded.sort_order;`)
}

// Phases come after the items: closing_milestone_id references one.
for (const phase of seed.phases) {
  statements.push(`INSERT INTO phases (number, name, closing_milestone_id)
VALUES (${phase.number}, ${text(phase.name)}, ${nullable(phase.closingMilestoneId)})
ON CONFLICT(number) DO UPDATE SET
  name = excluded.name,
  closing_milestone_id = excluded.closing_milestone_id;`)
}

for (const blackout of seed.blackouts) {
  statements.push(`INSERT INTO blackouts (from_date, to_date, reason)
VALUES (${text(blackout.from)}, ${text(blackout.to)}, ${text(blackout.reason)})
ON CONFLICT(from_date) DO UPDATE SET
  to_date = excluded.to_date,
  reason = excluded.reason;`)
}

seed.dimensions.forEach((dimension, index) => {
  statements.push(`INSERT INTO dimensions (name, sort_order)
VALUES (${text(dimension)}, ${index + 1})
ON CONFLICT(name) DO UPDATE SET sort_order = excluded.sort_order;`)
})

for (const [skill, dimension] of Object.entries(seed.skills)) {
  statements.push(`INSERT INTO skills (name, dimension)
VALUES (${text(skill)}, ${text(dimension)})
ON CONFLICT(name) DO UPDATE SET dimension = excluded.dimension;`)
}

// Validator metadata lives in the database too, so an export is lossless: a
// fresh machine gets back the rules the content is checked against, not just
// the content.
const meta = {
  time_zone: seed.timeZone,
  seed_version: version,
  expected_items_per_phase: JSON.stringify(seed.expectedItemsPerPhase),
  phase_windows: JSON.stringify(seed.phaseWindows),
  milestone_dependency_exceptions: JSON.stringify(seed.milestoneDependencyExceptions),
}

for (const [key, value] of Object.entries(meta)) {
  statements.push(`INSERT INTO meta (key, value) VALUES (${text(key)}, ${text(value)})
ON CONFLICT(key) DO UPDATE SET value = excluded.value;`)
}

mkdirSync(new URL('build/', root), { recursive: true })
writeFileSync(
  new URL('build/seed.sql', root),
  `-- Generated by tools/seed/to-sql.mjs from ${input} — do not edit.\n` +
    `-- Seed version ${version}: ${seed.items.length} items, ${seed.phases.length} phases, ` +
    `${Object.keys(seed.skills).length} skills.\n\n` +
    `${statements.join('\n\n')}\n`,
)

console.log(
  `build/seed.sql — ${seed.items.length} items, ${seed.phases.length} phases, ` +
    `${seed.blackouts.length} blackouts, ${Object.keys(seed.skills).length} skills, ` +
    `seed version ${version}`,
)
